export interface Municipio {
  municipio: number,
  uf: number,
  uf_code: string,
  name: string,
  mesoregion: number,
  microregion: number,
  rgint: number,
  rgi: number,
  osm_relation_id: number,
  wikidata_id: string,
  is_capital: string,
  wikipedia_pt: string,
  lon: number,
  lat: number,
  no_accents: string,
  slug_name: string,
  alternative_names: string,
  pop_21: number,
}
